version: "3.1"
services:

    mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      container_name: docker-symfony4-mysql
      working_dir: /app
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=docker_symfony4
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=dbpw
      ports:
        - "3306:3306"

   

    php-apache:
      build: docker-firma
      container_name: docker-symfony4-php-apache
      working_dir: /app
      volumes:
        - .:/app        
      ports:
        - "443:443"